openapi: "3.0.1"
info:
  title: "textchart"
  version: "1.0.0"
servers:
- url: "https://plantuml.textchart.com"
paths:
  /img/{id}:
    get:
      operationId: "get-png"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Content-Type:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        uri: "http://IP/img/{id}"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Content-Type: "integration.response.header.Content-Type"
              method.response.header.Access-Control-Allow-Origin: "'*.textchart.com'"
            contentHandling: "CONVERT_TO_BINARY"
        requestParameters:
          integration.request.path.id: "method.request.path.id"
        passthroughBehavior: "when_no_match"
        httpMethod: "GET"
        type: "http"
components: {}
x-amazon-apigateway-binary-media-types:
- "image/png"
:
